In [2]:
! pwd

/Users/mohituniyal/Documents/Coding/Coding Blocks/Workshops/Galgotias Uni


In [3]:
! pip install numpy

You should consider upgrading via the 'pip install --upgrade pip' command.


In [4]:
import numpy as np

In [14]:
ar1 = np.array([1,4,6,8])
ar2 = np.array([7,8,9,2])

In [15]:
type(ar1)

numpy.ndarray

In [16]:
ar1*ar2

array([ 7, 32, 54, 16])

In [17]:
ar1**2

array([ 1, 16, 36, 64])

In [20]:
ar1.shape

(4,)

In [27]:
ar1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [28]:
ar1.shape

(3, 3)

In [30]:
ar1[1 , 1]

5

In [37]:
# Array Slicing
# arr[ rows ,  cols  ]
ar1[  1 : 2 ,  :  ]

array([[4, 5, 6]])

In [38]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
ar1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
ar2 = np.array([[1],
                [2],
                [3]])

In [43]:
np.dot(ar1, ar2)

array([[14],
       [32],
       [50]])

In [45]:
5*ar1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
ar2

array([[1],
       [2],
       [3]])

In [48]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
ar2+ar1

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [52]:
ar1>4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [54]:
np.sum(ar1)

45

In [55]:
def distance(pA, pB):
    return np.sqrt(np.sum((pB - pA)**2))

In [60]:
a = np.array([5,5, 6,8,9])
b = np.array([0,1,4,7,0])

In [61]:
distance(a,b)

11.269427669584644

In [63]:
np.sin(90)

0.8939966636005579

In [72]:
np.random.randint(10, 100, size= (3,3) )

array([[63, 67, 50],
       [31, 38, 89],
       [36, 43, 49]])